### ISSUE TITLE
long run time when set m=365

### ISSUE THREAD

**Issue by sattar-hazrati** [tgsmith61591/pmdarima#102]
#### Description

I  have one year daily data. and want to predict 30 days. for this work i set this parameters
arima = pm.auto_arima(train, error_action='ignore', trace=1,seasonal=True, m=365)
my problem is that  very long run time for each model
is it correct  to set m= 365 for daily data?

**Comment by tgsmith61591** [comment]
Hey Sattar! Thanks for filing an issue.

This is a known issue with seasonal ARIMAs with large `m` values. In our next release (v1.2.0) we will be adding new tests of seasonality which should help speed things up (see #88). Currently, seasonal differencing tests default to the CH (canova-hansen) test. We've got OCSB implemented and it will be the new default in v1.2.0, so you should see some speed-ups there.

That said, though, at the end of the day seasonal ARIMAs with large `m` are always going to run a big slow. Since we delegate those model fits down to statmodels, there's not a ton that can be done for that... even R chokes on those models. :-(

If you'd like to build the bleeding edge and try your model with the `OCSB` test (default), you'll have to build the package from source:

```bash
$ git clone -b develop git@github.com:tgsmith61591/pmdarima.git
$ cd pmdarima
$ python setup.py develop
```

**Comment by RahatKatal** [comment]
Hi Sattar,

Did you find a work around long period of seasonality i.e. large value of m? I am also facing the same issue currently.

**Comment by tgsmith61591** [comment]
Closing since #103 is the exact same, but with more detail
