### ISSUE TITLE
How can I load trained models with Python 2.7?

### ISSUE THREAD

**Issue by venegas09** [tgsmith61591/pmdarima#110]
#### Description
I want to use a trained model in AWS Lambda and then deploy it on AWS Sagemaker, for local use. The problem is that AWS Lambda in Sagemaker just allows using Python 2.7 so I have to use pmdarima 0.9.0 as highest for the prediction, but I have this issue #107 when reading the trained model. So my question is If there is anything I can do for using pmdarima 0.9.0 without having the #107 issue? 

My idea is to train a model on Sagemaker, and then deploy it on AWS Greengrass for local predictions. So I need to run the predictions on Python 2.7.
#### Versions
Windows-10-10.0.17763
('Python', '2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)]')
('pmdarima', '0.9.0')
('NumPy', '1.16.2')
('SciPy', '1.2.1')
('Scikit-Learn', '0.20.3')
('Statsmodels', '0.9.0')

**Comment by tgsmith61591** [comment]
Sagemaker is container-based. Can you create a docker image with python 3.5+ and store it in your ECR registry? Paging @charlesdrotar for this one, since he's the AWS expert

**Comment by venegas09** [comment]
Yes, I can create and train the model with python 3.5+ in Sagemaker, but then I want to use it in AWS Lambda that only allows Python 2.7, so it breaks.

**Comment by aaronreidsmith** [comment]
Lambda allows [2.7, 3.6, and 3.7](https://aws.amazon.com/about-aws/whats-new/2018/11/aws-lambda-supports-python-37/), as far as I know. I usually run 3.6 in Lambda

**Comment by venegas09** [comment]
Sorry, I mean Lambda in AWS Sagemaker

**Comment by aaronreidsmith** [comment]
I am not well-versed in Sagemaker, but just looking at their demo docs, they have an example in 3.7 (pre-labeling) and 2.7 (post-labeling) ([link](https://docs.aws.amazon.com/sagemaker/latest/dg/sms-custom-templates-step2-demo1.html)). I can't find anything that says they explicitly only support 2.7, could you link me to that?

**Comment by venegas09** [comment]
AWS Greengrass just support Python 2.7 for AWS Lambda functions (maybe you read the previous post that I wrote wrong :( ): [https://aws.amazon.com/greengrass/faqs/?nc1=h_ls](url)

**Comment by tgsmith61591** [comment]
Deviating a bit, the issue you posted yesterday (#107) alludes to the fact that even though you're using pmdarima 0.9.0, your model was probably trained and pickled in an earlier version. Is that correct?

**Comment by venegas09** [comment]
Yes, I solved that issue. I just had to train it with the latest version (1.1.0)
Thanks! :)

**Comment by tgsmith61591** [comment]
Woohoo! I'll close it out then. If anything else comes up, feel free to reach out.

**Comment by tgsmith61591** [comment]
@venegas09 this is sounding like a separate issue, if you're getting an ImportError. Also, the updated comments are showing GreenGrass, etc., rather than Sage Maker. This may be a larger issue than is applicable to the package itself. It might be worth us putting together a page in the doc that shows a repeatable pattern for such architectures.

**Comment by venegas09** [comment]
But I guess that the importError is because I have trained the model with pmdarima 1.1.0 and then i'm loading it in a machine without that library, because it just uses Python2.7. Could it be possible to train a model in pmdarima 1.1.0 and then make the prediction using pyramid-arima 0.9.0 library?

**Comment by tgsmith61591** [comment]
I think this has gone way outside of the scope of the original issue. We decided to stop supporting 2.7 since it is so near end of life, and distributing 5 extra wheels in our CI jobs was so expensive time-wise. That said, there is no overt code that would break 2.7 compat, to my knowledge. You can clone, change this line in the setup.py:

```python
python_requires='>=3.5'
```

And build from source:

```bash
$ make install
```

You will need Cython.

Now, to address your specific question, perhaps I'll get around to writing a blog post on it someday. But it's far too specific to handle here in the issue board.

**Comment by venegas09** [comment]
I don't know why but I can't install it from source... I'm in a Windows 10 machine

**Comment by tgsmith61591** [comment]
https://www.alkaline-ml.com/pmdarima/setup.html#build-from-source
