### ISSUE TITLE
Feature Request: Bayesian Optimization

### ISSUE THREAD

**Issue by rohan-gt** [tgsmith61591/pmdarima#115]
Can the hyperparameters of auto-ARIMA be optimized by Bayesian optimization using packages like Hyperopt for faster modelling?

**Comment by tgsmith61591** [comment]
This is one I'll have to think on for a while. As it currently stands, you couldn't easily sub in a new backend seamlessly, but that's because that was the behavior R's `auto.arima` set as precedent. I'm not saying that's the *only* way, or the proper way, just explaining why it is the way it is.

That said, if hyperopt or other hyper-param search methods can be shown to out-perform the stepwise algorithm that Hyndman laid out, then I think it's worth including for sure.

I'm going to mark this as backlog for now, since I think it's more of a convenience feature than anything else.

**Comment by tgsmith61591** [comment]
I'm going to close this since I don't see it as being very high priority. If anyone ever wants to take a crack at it, feel free to comment as such.
