### ISSUE TITLE
How are the parameters d,D, max_d, max_D exactly working?

### ISSUE THREAD

**Issue by vibhashahani** [tgsmith61591/pmdarima#123]
What does the parameter max_d and max_D exactly do?
My concern is - if I mention max_d = 2 so is it taking all possible values of d from 0 to 2 or how is it working?
Similarly with max_D

**Comment by tgsmith61591** [comment]
Your intuition is correct. In your case, it would search from 0 to 2. The caveat is `max_order` also plays a role. If `max_order` is 5, for instance, `order` can never equal, say, `(2, 2, 2)`, since it sums to greater than 5. You can always set `max_order=None` to allow this behavior.

If you explicitly *set* `d` or `D`, however, `max_d` and `max_D` won't matter and the method won't search over those parameters.
