### ISSUE TITLE
auto_arima() stops well before reaching max_p and max_q

### ISSUE THREAD

**Issue by Bautista-Baiocchi-lora** [tgsmith61591/pmdarima#192]
Hello,

I am trying to utilize the auto_arima() method to conduct a stepwise search of my optimal max_p and max_q. The method seems to finish gracefully before actually testing all the p and q values.

Run the following code in a jupyter lab notebook env.

```python
from AI import x
import pandas as pd
import numpy as np
from pyramid.arima import auto_arima
stepwise_fit = auto_arima(x.price, start_p=1, start_q=1,
                             max_p=20, max_q=20,
                             d=1,max_d=1, trace=True,
                             suppress_warnings=True,  # don't want convergence warnings
                             stepwise=True)  # set to stepwise
```

**Versions**
 3 import pmdarima; print("pmdarima", pmdarima.__version__)
      4 import numpy; print("NumPy", numpy.__version__)
      5 import scipy; print("SciPy", scipy.__version__)

ModuleNotFoundError: No module named 'pmdarima'
-->

**Expected behavior**
The function should test all the p and q values.

**Actual behavior**
Fit ARIMA: order=(1, 1, 1) seasonal_order=(0, 0, 0, 1); AIC=-17276.939, BIC=-17247.111, Fit time=0.908 seconds
Fit ARIMA: order=(0, 1, 0) seasonal_order=(0, 0, 0, 1); AIC=-17195.211, BIC=-17180.298, Fit time=1.127 seconds
Fit ARIMA: order=(1, 1, 0) seasonal_order=(0, 0, 0, 1); AIC=-17278.842, BIC=-17256.472, Fit time=0.565 seconds
Fit ARIMA: order=(0, 1, 1) seasonal_order=(0, 0, 0, 1); AIC=-17278.753, BIC=-17256.382, Fit time=1.318 seconds
Fit ARIMA: order=(2, 1, 0) seasonal_order=(0, 0, 0, 1); AIC=-17276.932, BIC=-17247.104, Fit time=1.619 seconds
Fit ARIMA: order=(2, 1, 1) seasonal_order=(0, 0, 0, 1); AIC=-17274.940, BIC=-17237.656, Fit time=2.930 seconds
Total fit time: 8.469 seconds

**Additional context**
My machine python shows I don't have pmdarima installed. This should not matter because it is installed in the juptyer lab env.

**Comment by tgsmith61591** [comment]
There are a few things at play here. First of all, you're using an *extremely* outdated version of the package. The `ModuleNotFoundError` is correct&mdash;you don't have `pmdarima` installed, because you're using `pyramid`, the old namespace. See issue #34 & #46 for context, but you should use the latest version, or at least the new namespace.

Secondly, there is a param called `max_order` that controls the maximum order of your model. It defaults to 10. See [the documentation](https://www.alkaline-ml.com/pmdarima/modules/generated/pmdarima.arima.auto_arima.html#pmdarima.arima.auto_arima) for more understanding. The stepwise algorithm is also sophisticated enough to know not to just brute force every combination; if that's the goal, then don't use stepwise. See [this docstring](https://github.com/tgsmith61591/pmdarima/blob/master/pmdarima/arima/_auto_solvers.py#L15) for better understanding.
