### ISSUE TITLE
pipeline does not support predict_in_sample

### ISSUE THREAD

**Issue by ihadanny** [tgsmith61591/pmdarima#196]
created a pipeline, now I would like to visualize the goodness of my fit.
would be neat to simply write: `pipe.predict_in_sample()`.

I also tried `pipe.steps[2][1].predict_in_sample()` but got: `ValueError: When an ARIMA is fit with an exogenous array, it must also be provided one for predicting or updating observations.`

**Comment by tgsmith61591** [comment]
This is a really great feature request, thanks. Given your other request on #195 I'm guessing you're using the pipeline to create your Fourier features, which you don't have in an exogenous array outside of the pipeline, which is why calling the ARIMA object directly won't work.

Let me work something up

**Comment by tgsmith61591** [comment]
Merged in #198
