### ISSUE TITLE
Best Model Question

### ISSUE THREAD

**Issue by geoagr2003** [tgsmith61591/pmdarima#229]
Hi,

Because I have interest in doing Time Series analysis I started looking into your project :)

There are some cool features implemented so far!

What I want to ask is the following:

I looked into the results.summary() of my best model obtained with pmdarima.auto_arima() and I noticed that p-value(s) that reflects the residuals values used in results.plot_diagnostics() may not be good. Only one of them (Prob(Q) or Prob(JB)) have some time value greater than 0.05. Far as I know, and read about, both must be greater than 0.05 in order to have a best model. The residuals must be uncorrelated and normally distributed. I'm not sure if the minimum AIC is enough, we must have also resiudals in the previous mentioned condition, if they are not in this condition the model must be reworked. I assume that in this condition the looping through the possible models should go on. Is this judgement correct?

I also take a look in the obtained model (in results) and there is something like this "scoring='mse'". It means that the pmdarima.auto_arima() algorithm is splitting also the provided data and make an in-side prediction test? If is so can you tell me the proportion of the used data in this test?

I used this tool to find the best SARIMA model for some monthly time series. I used the following lines:

```python
# I split my data in 0.8 for training and 0.2 for testing
kpss_diffs = ndiffs(train, alpha=0.05, test='kpss', max_d=12)
adf_diffs = ndiffs(train, alpha=0.05, test='adf', max_d=12)
d = max(adf_diffs, kpss_diffs)

D = nsdiffs(train, m=12, max_D=12, test='ocsb')

results = pm.auto_arima(
    train, # data
    # Non-Seasonal Parameters
    d=d, # non-seasonal difference order
    start_p=0, max_p=12,
    start_q=0, max_q=12,
    # Seasonal Parameters
    seasonal=True,
    m=12, # the seasonal period (12 months) = the number of periods in each season
    D=D, # seasonal difference order
    start_P=0, max_P=12,
    start_Q=0, max_Q=12,
    information_criterion='aic', # used to select the best model
    stepwise=True, # apply inteligent order search
    suppress_warnings=True, # disable general warnings                      
    error_action="ignore" # disable ModelFitWarning(s)
)
results.summary()
```

Best regards,
George C.

**Comment by tgsmith61591** [comment]
Hi George,

There's a lot going on in this question, so let me try to address it in chunks.

> I looked into the results.summary() of my best model obtained with pmdarima.auto_arima() and I noticed that p-value(s) that reflects the residuals values used in results.plot_diagnostics() may not be good. Only one of them (Prob(Q) or Prob(JB)) have some time value greater than 0.05. Far as I know, and read about, both must be greater than 0.05 in order to have a best model.

I won't go too far into P-values, but it's useful to note that the P-values to which you're referring achieve two entirely separate tasks. The Jarque-Bera test is of normality, while the Ljung-Box test is a test of non-autocorrelation (Rob Hyndman has [some really great thoughts on it](https://robjhyndman.com/hyndsight/ljung-box-test/), should you be interested). One thing he says that I think is really important to consider:

> "...we expect the resid­u­als to fail this test when we have suf­fi­cient data."

It's worth noting that his work on `forecast::auto.arima` does not consider results of the Ljung-Box test in model selection, which is why ours doesn't either.

Secondly, regarding the question on `scoring='mse'`

> I also take a look in the obtained model (in results) and there is something like this "scoring='mse'". It means that the pmdarima.auto_arima() algorithm is splitting also the provided data and make an in-side prediction test? If is so can you tell me the proportion of the used data in this test?

This has to do with the parameter `out_of_sample_size`. If you had chosen to set this value to, say, 10, the model would have been fit on the first `k - 10` samples, and you could have selected your model on the basis of how it performed ('mse') against the held-out fold of samples. This behavior is going to disappear in the future in favor of some of the more granular control recent releases have given us over [cross validation](https://www.alkaline-ml.com/pmdarima/modules/classes.html#pmdarima-model-selection-cross-validation-classes). For instance:

```python
import numpy as np
import pmdarima as pm
from pmdarima import model_selection

data = pm.datasets.load_wineind()
train, test = data[:165], data[165:]

model1 = pm.ARIMA(order=(2, 1, 1), seasonal_order=(0, 0, 0, 1))
model2 = pm.ARIMA(order=(1, 1, 2), seasonal_order=(0, 1, 1, 12))
cv = model_selection.SlidingWindowForecastCV(window_size=100, step=24, h=1)

model1_cv_scores = model_selection.cross_val_score(
    model1, train, scoring='smape', cv=cv, verbose=2)

model2_cv_scores = model_selection.cross_val_score(
    model2, train, scoring='smape', cv=cv, verbose=2)

print("Model 1 CV scores: {}".format(model1_cv_scores.tolist()))  # [23.928976841681518, 22.289666122815046, 3.7484080171047283]
print("Model 2 CV scores: {}".format(model2_cv_scores.tolist()))  # [1.4413474767581218, 15.413429218463346, 5.572225774148651]
```

Hope this helps out some.
